feat: add min_instances parameter.
terraform-google-modules/terraform-google-scheduled-function pull request #111
Opened 2023-03-18 13:00 UTC by savioteles

This PR adds the min_instances parameter. The limit on the minimum number of fnction instances that may coexist at a given time.

**Reference**
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudfunctions_function#min_instances

2023-04-13 09:11 UTC, savioteles commented
@bharathkkb can you review? This PR adds the `min_instances` parameter.

2023-05-12 02:09 UTC, bharathkkb commented
/gcbrun

2023-05-12 02:36 UTC, bharathkkb requested changes
Thanks for the PR and sorry for the delay @savioteles

2023-05-12 02:36 UTC, bharathkkb commented on main.tf
> +  min_instances                      = var.function_min_instances
We will need to add support for this in the [event-function module](https://github.com/terraform-google-modules/terraform-google-event-function) first

2023-07-19 23:02 UTC, closed without merging