Add option for VPC connector
terraform-google-modules/terraform-google-scheduled-function pull request #59
Opened 2021-07-05 10:17 UTC by boxcee

2021-08-12 19:15 UTC, morgante commented
@boxcee Please reformat, per the contributing guide.

2021-08-12 19:33 UTC, boxcee commented
@googlebot I signed it!

2021-08-12 20:00 UTC, morgante requested changes

2021-08-12 20:00 UTC, morgante commented on variables.tf
> +variable "function_vpc_connector" {
Since this is all part of a function module, `function_` seems redundant.

```suggestion
variable "vpc_connector" {
```

2021-08-12 20:00 UTC, morgante commented on variables.tf
> +variable "function_vpc_connector_egress_settings" {
```suggestion
variable "vpc_connector_egress_settings" {
```

2021-08-13 05:53 UTC, boxcee commented
@morgante Done.

2021-08-13 14:49 UTC, morgante approved these changes

2021-08-13 14:49 UTC, merged